baseURL: "https://vollkorntomate.eu/"
title: "vollkorntomate"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
theme: "PaperMod"
pagination:
  pagerSize: 10
copyright: © 2025 [vollkorntomate](https://vollkorntomate.eu) • This work is openly licensed via [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
titleCaseStyle: none

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "EN"
    weight: 1
    taxonomies:
      category: "categories"
      tag: "tags"
      series: "series"
    menu:
      main:
        - name: "About me"
          weight: 10
          identifier: "about"
          url: "/about/"
        - name: "Projects"
          weight: 20
          identifier: "projects"
          url: "/projects/"
        - name: "Blog"
          weight: 30
          identifier: "blog"
          url: "/blog/"
        - name: "CTF Writeups"
          weight: 40
          identifier: "ctf-writeups"
          url: "/ctf-writeups/"

params:
  env: production
  description: "vollkorntomate – Security Researcher, Programmer, Open Source Advocate"
  images: ["images/vollkorntomate-small.jpeg"]

  defaultTheme: auto
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  displayFullLangName: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false

  profileMode:
    enabled: true
    title: "vollkorntomate"
    subtitle: "Security Researcher, Programmer, Open Source Advocate"
    imageUrl: "images/vollkorntomate.jpg"
    imageTitle: "Profile image"

  socialIcons:
    - name: "github"
      title: "GitHub"
      url: "https://github.com/vollkorntomate/"
    - name: "codeberg"
      title: "Codeberg"
      url: "https://codeberg.org/vollkorntomate/"
    - name: "stackoverflow"
      title: "StackOverflow"
      url: "https://stackoverflow.com/users/10295689/vollkorntomate"
    - name: "orcid"
      title: "ORCiD: 0009-0004-1051-1549"
      url: "https://orcid.org/0009-0004-1051-1549"
    # - name: "ctftime"
    #   title: "CTFTime"
    #   url: "https://ctftime.org/user/150460"
    # - name: "hackerone"
    #   title: "hackerone"
    #   url: "https://hackerone.com/vollkorntomate?type=user"
    # - name: "bugcrowd"
    #   title: "Bugcrowd"
    #   url: "https://bugcrowd.com/vollkorntomate"
    # - name: "tryhackme"
    #   title: "TryHackMe"
    #   url: "https://tryhackme.com/vollkorntomate"
    - name: "hackthebox"
      title: "HackTheBox"
      url: "https://app.hackthebox.com/users/836509"
    - name: "pgpkey"
      title: "PGP Public Key (Fingerprint: 0x36FB1BADEB61C4469C375E913289CE3A5D057650)"
      url: "files/gpg-pubkey-vollkorntomate.asc"
    - name: "mastodon"
      title: "Mastodon"
      url: "https://infosec.exchange/@vollkorntomate"
    # - name: "matrix"
    #   title: "Matrix"
    #   url: "https://matrix.to/#/@thomas:vollkorntomate.de"

  social:
    fediverse_creator: "@vollkorntomate@infosec.exchange"

  label:
    text: "vollkorntomate"
    icon: "images/vollkorntomate.jpg"
    iconHeight: 25

  assets:
    disableHLJS: true
    favicon: "images/favicon-32x32.png"
    favicon16x16: "images/favicon-16x16.png"
    favicon32x32: "images/favicon-32x32.png"
    apple_touch_icon: "images/apple-touch-icon.png"
    safari_pinned_tab: "images/apple-touch-icon.png"

markup:
  goldmark:
    renderer:
      unsafe: false
  highlight:
    noClasses: false
    # anchorLineNos: false
    # codeFences: true
    # guessSyntax: false
    # hl_Lines: ""
    # hl_inline: false
    # lineAnchors: ""
    # lineNoStart: 1
    # lineNos: false
    # lineNumbersInTable: true
    # style: monokai
    # tabWidth: 4
    # wrapperClass: highlight
